#!/usr/bin/env bash

# Automated file & database backup via Restic
# Min. Requirement  : GNU/Linux Ubuntu 20.04
# Last Build        : 25/09/2026
# Author            : MasEDI.Net (me@masedi.net)
# Since Version     : 2.6.7

# Include helper functions.
if [[ "$(type -t run)" != "function" ]]; then
    BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
    # shellcheck disable=SC1091
    . "${BASE_DIR}/utils.sh"

    # Make sure only root can run this installer script.
    requires_root "$@"

    # Make sure only supported distribution can run this installer script.
    preflight_system_check
fi

# Default locations (target-system absolute paths).
BACKUP_KEY_FILE="/etc/lemper/backup.key"
BACKUP_SCRIPT="/etc/lemper/backup.sh"
BACKUP_CRON_FILE="/etc/cron.d/lemper-backup"
BACKUP_LOG_FILE="/var/log/lemper-backup.log"

##
# Install Restic binary.
# Distro apt ships a stale restic (Ubuntu 24.04: 0.16.4, Debian 12: 0.14.0),
# so install the official GitHub release binary instead.
# Ref: https://github.com/restic/restic/releases
##
function install_restic_binary() {
    local RESTIC_VERSION=${RESTIC_VERSION:-"latest"}
    local RESTIC_ARCH=""
    local RESTIC_TAG=""
    local RESTIC_DOWNLOAD_LINK=""

    # Detect CPU architecture.
    case "$(uname -m)" in
        x86_64)
            RESTIC_ARCH="amd64"
        ;;
        aarch64 | arm64)
            RESTIC_ARCH="arm64"
        ;;
        *)
            error "Unable to install Restic, unsupported architecture: $(uname -m)."
            return 1
        ;;
    esac

    # Resolve "latest" to the actual release tag.
    if [[ "${RESTIC_VERSION}" == "latest" ]]; then
        echo "Resolving latest Restic release..."
        local LATEST_URL && \
        LATEST_URL=$(curl -fsSL -o /dev/null -w '%{url_effective}' "$(gh_url "https://github.com/restic/restic/releases/latest")")
        RESTIC_TAG="${LATEST_URL##*/}"
        RESTIC_VERSION="${RESTIC_TAG#v}"

        if [[ -z "${RESTIC_VERSION}" ]]; then
            error "Unable to resolve latest Restic release tag."
            return 1
        fi

        echo "Latest Restic release: ${RESTIC_VERSION}"
    fi

    # Restic release asset URL pattern:
    # https://github.com/restic/restic/releases/download/v0.19.1/restic_0.19.1_linux_amd64.bz2
    RESTIC_DOWNLOAD_LINK="$(gh_url "https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_linux_${RESTIC_ARCH}.bz2")"

    echo "Installing Restic ${RESTIC_VERSION} from release binary..."

    local CURRENT_DIR && \
    CURRENT_DIR=$(pwd)
    run cd "${BUILD_DIR}" || return 1

    # bzip2 is required to extract the release asset.
    if [[ -z $(command -v bunzip2) ]]; then
        run apt-get install -q -y bzip2
    fi

    if curl -sLI "${RESTIC_DOWNLOAD_LINK}" | grep -q "HTTP/[.12]* [2].."; then
        run curl -sSL -o "restic_${RESTIC_VERSION}_linux_${RESTIC_ARCH}.bz2" "${RESTIC_DOWNLOAD_LINK}" && \
        run bunzip2 -f "restic_${RESTIC_VERSION}_linux_${RESTIC_ARCH}.bz2" && \
        run install -m 0755 "restic_${RESTIC_VERSION}_linux_${RESTIC_ARCH}" /usr/local/bin/restic && \
        run rm -f "restic_${RESTIC_VERSION}_linux_${RESTIC_ARCH}"
    else
        error "Restic release asset not found: ${RESTIC_DOWNLOAD_LINK}"
        run cd "${CURRENT_DIR}" || return 1
        return 1
    fi

    run cd "${CURRENT_DIR}" || return 1

    if [[ -n $(command -v restic) ]]; then
        success "Restic $(restic version | head -n 1) installed successfully."
    else
        error "Something went wrong with Restic installation."
        return 1
    fi
}

##
# Write the scheduled backup runner script (/etc/lemper/backup.sh).
# The script dumps databases, backs up files with Restic, and prunes snapshots.
##
function write_backup_script() {
    local BACKUP_REPO="${1}"
    local BACKUP_PATHS_RAW="${2}"

    if [[ "${DRYRUN}" == true ]]; then
        info "Backup runner script would be written to ${BACKUP_SCRIPT} (dry run)."
        return 0
    fi

    echo "Writing backup runner script to ${BACKUP_SCRIPT}..."

    run mkdir -p /etc/lemper && run chmod 0700 /etc/lemper

    # Quoted heredoc: nothing is expanded here; %%TOKENS%% are replaced below.
    cat > "${BACKUP_SCRIPT}" <<'LEMPER_BACKUP_EOF'
#!/usr/bin/env bash
#
# LEMPer automated backup (Restic).
# Generated by LEMPer install_backup.sh - safe to regenerate, do not edit manually.
#
# What it does:
#   1. Initializes the Restic repository if absent.
#   2. Dumps all MariaDB/MySQL databases (if installed) and all
#      PostgreSQL databases (if installed) into the dump directory.
#   3. Backs up /home (user data + web roots), /etc/lemper and /etc/nginx.
#   4. Prunes old snapshots (keep 7 daily, 4 weekly, 6 monthly).

set -e -o pipefail

BACKUP_REPO="%%BACKUP_REPO%%"
BACKUP_KEY="%%BACKUP_KEY%%"
DB_DUMP_DIR="%%DB_DUMP_DIR%%"
LEMPER_CONF="%%LEMPER_CONF%%"
LOG_FILE="%%LOG_FILE%%"

export RESTIC_PASSWORD_FILE="${BACKUP_KEY}"
export RESTIC_REPOSITORY="${BACKUP_REPO}"

log() {
    echo "[$(date '+%F %T')] $*" >> "${LOG_FILE}"
}

if [[ -z $(command -v restic) ]]; then
    log "ERROR: restic binary not found, backup aborted."
    exit 1
fi

if [[ ! -f "${BACKUP_KEY}" ]]; then
    log "ERROR: backup key ${BACKUP_KEY} not found, backup aborted."
    exit 1
fi

mkdir -p "${DB_DUMP_DIR}" "$(dirname "${BACKUP_REPO}")"
chmod 700 "${DB_DUMP_DIR}"
touch "${LOG_FILE}" && chmod 600 "${LOG_FILE}"

# Initialize the repository on first run.
if ! restic cat config >/dev/null 2>&1; then
    log "Initializing Restic repository at ${BACKUP_REPO}..."
    restic init >> "${LOG_FILE}" 2>&1
fi

# Database credentials saved by the LEMPer installer.
MYSQL_ROOT_PASSWORD=""
if [[ -f "${LEMPER_CONF}" ]]; then
    MYSQL_ROOT_PASSWORD=$(grep -E '^MYSQL_ROOT_PASSWORD=' "${LEMPER_CONF}" | tail -n 1 | cut -d '=' -f 2-)
fi

# --- Database dumps ---
DUMP_BIN=""
if [[ -n $(command -v mariadb-dump) ]]; then
    DUMP_BIN=$(command -v mariadb-dump)
elif [[ -n $(command -v mysqldump) ]]; then
    DUMP_BIN=$(command -v mysqldump)
fi

if [[ -n "${DUMP_BIN}" ]]; then
    # Pass the password via a temp defaults file so it never shows in ps output.
    MYCNF=$(mktemp /tmp/lemper-mycnf.XXXXXX)
    chmod 600 "${MYCNF}"
    printf '[client]\nuser="root"\npassword="%s"\n' "${MYSQL_ROOT_PASSWORD}" > "${MYCNF}"
    log "Dumping all MySQL/MariaDB databases..."
    if "${DUMP_BIN}" --defaults-extra-file="${MYCNF}" --all-databases \
        --single-transaction --quick --routines --events \
        > "${DB_DUMP_DIR}/mariadb-all-databases.sql" 2>>"${LOG_FILE}"; then
        log "MySQL/MariaDB dump completed."
    else
        log "WARNING: MySQL/MariaDB dump failed, continuing without it."
    fi
    rm -f "${MYCNF}"
fi

if [[ -n $(command -v pg_dumpall) ]]; then
    log "Dumping all PostgreSQL databases..."
    if sudo -n -u postgres pg_dumpall > "${DB_DUMP_DIR}/postgres-all-databases.sql" 2>>"${LOG_FILE}"; then
        log "PostgreSQL dump completed."
    else
        log "WARNING: PostgreSQL dump failed, continuing without it."
    fi
fi

# --- File backup ---
BACKUP_PATHS=()
BACKUP_PATHS+=("${DB_DUMP_DIR}")
for p in %%BACKUP_PATHS_RAW%%; do
    if [[ -e "${p}" ]]; then
        BACKUP_PATHS+=("${p}")
    else
        log "Skipping missing path: ${p}"
    fi
done

log "Starting Restic backup of: ${BACKUP_PATHS[*]}"
if restic backup --tag lemper-auto "${BACKUP_PATHS[@]}" >> "${LOG_FILE}" 2>&1; then
    log "Backup completed successfully."
else
    RC=$?
    log "ERROR: Restic backup failed with exit code ${RC}."
    exit "${RC}"
fi

# --- Retention: keep 7 daily, 4 weekly, 6 monthly snapshots ---
log "Pruning old snapshots..."
if restic forget --prune --keep-daily 7 --keep-weekly 4 --keep-monthly 6 >> "${LOG_FILE}" 2>&1; then
    log "Prune completed."
else
    log "WARNING: snapshot prune failed."
fi

log "Backup run finished."
LEMPER_BACKUP_EOF

    # Replace baked-in tokens (target-system absolute paths only).
    run sed -i "s|%%BACKUP_REPO%%|${BACKUP_REPO}|g; \
s|%%BACKUP_KEY%%|${BACKUP_KEY_FILE}|g; \
s|%%DB_DUMP_DIR%%|${BACKUP_REPO}/db-dumps|g; \
s|%%LEMPER_CONF%%|/etc/lemper/lemper.conf|g; \
s|%%LOG_FILE%%|${BACKUP_LOG_FILE}|g; \
s|%%BACKUP_PATHS_RAW%%|${BACKUP_PATHS_RAW}|g" "${BACKUP_SCRIPT}"

    run chmod 0700 "${BACKUP_SCRIPT}"

    success "Backup runner script installed at ${BACKUP_SCRIPT}."
}

##
# Register the backup cron job per BACKUP_SCHEDULE (daily | weekly).
##
function register_backup_cron() {
    local CRON_SCHEDULE=""

    case "${BACKUP_SCHEDULE:-daily}" in
        daily)
            # Every day at 02:00.
            CRON_SCHEDULE="0 2 * * *"
        ;;
        weekly)
            # Every Sunday at 03:00.
            CRON_SCHEDULE="0 3 * * 0"
        ;;
        *)
            warning "Unknown BACKUP_SCHEDULE '${BACKUP_SCHEDULE}', falling back to daily."
            CRON_SCHEDULE="0 2 * * *"
        ;;
    esac

    if [[ "${DRYRUN}" == true ]]; then
        info "Cron job '${CRON_SCHEDULE} root ${BACKUP_SCRIPT}' would be registered (dry run)."
        return 0
    fi

    echo "Registering backup cron job (${BACKUP_SCHEDULE:-daily})..."

    cat > "${BACKUP_CRON_FILE}" <<CRON_EOF
# LEMPer automated backup (Restic).
# Generated by LEMPer install_backup.sh - safe to regenerate.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
${CRON_SCHEDULE} root ${BACKUP_SCRIPT} >/dev/null 2>&1
CRON_EOF

    run chmod 0644 "${BACKUP_CRON_FILE}"

    success "Backup cron job registered in ${BACKUP_CRON_FILE}."
}

##
# Install automated backup (Restic).
##
function init_backup_install() {
    local DO_INSTALL_BACKUP=""

    if [[ "${AUTO_INSTALL}" == true ]]; then
        if [[ "${INSTALL_BACKUP_TOOL}" == true ]]; then
            DO_INSTALL_BACKUP="y"
        else
            DO_INSTALL_BACKUP="n"
        fi
    else
        while [[ "${DO_INSTALL_BACKUP}" != "y" && "${DO_INSTALL_BACKUP}" != "Y" && \
            "${DO_INSTALL_BACKUP}" != "n" && "${DO_INSTALL_BACKUP}" != "N" ]]; do
            read -rp "Do you want to install automated backup (Restic)? [y/n]: " -e DO_INSTALL_BACKUP
        done
    fi

    if [[ ${DO_INSTALL_BACKUP} == y* || ${DO_INSTALL_BACKUP} == Y* ]]; then
        local BACKUP_TOOL=${BACKUP_TOOL:-"restic"}

        if [[ "${BACKUP_TOOL}" != "restic" ]]; then
            warning "Unsupported backup tool '${BACKUP_TOOL}', only 'restic' is implemented. Skipping."
            return 0
        fi

        # Install Restic binary if missing.
        if [[ -z $(command -v restic) || "${FORCE_INSTALL}" == true ]]; then
            install_restic_binary || return 1
        else
            info "Restic already exists, binary installation skipped."
        fi

        export BACKUP_REPO=${BACKUP_REPO:-"/var/backups/lemper"}

        # Auto-generate the repository password if empty.
        export BACKUP_PASSWORD=${BACKUP_PASSWORD:-$(openssl rand -base64 64 | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)}

        # Persist the generated password into .env when the shipped placeholder is empty.
        if [[ "${DRYRUN}" != true && -f "${ENVFILE}" ]] && \
            grep -qE '^BACKUP_PASSWORD=(""|)$' "${ENVFILE}"; then
            # Rewrite without sed replacement interpolation of the secret.
            _env_tmp=$(mktemp)
            grep -vE '^BACKUP_PASSWORD=' "${ENVFILE}" > "${_env_tmp}"
            printf 'BACKUP_PASSWORD="%s"\n' "${BACKUP_PASSWORD}" >> "${_env_tmp}"
            run cp -f "${_env_tmp}" "${ENVFILE}" && run chmod 600 "${ENVFILE}"
            run rm -f "${_env_tmp}"
        fi

        # Save credential to the LEMPer config.
        save_config -e "BACKUP_PASSWORD=${BACKUP_PASSWORD}"
        save_log -e "Backup credentials.\nRestic repository: ${BACKUP_REPO}, Restic repository password saved to /etc/lemper/lemper.conf and ${BACKUP_KEY_FILE}.\nSave this password, it is required to restore backups."

        if [[ "${DRYRUN}" != true ]]; then
            # Store the repository password in a root-only key file.
            # Never overwrite an existing key: it must match the repository.
            run mkdir -p /etc/lemper && run chmod 0700 /etc/lemper
            if [[ ! -f "${BACKUP_KEY_FILE}" ]]; then
                # No `bash -c` interpolation of the secret: printf feeds tee through a pipe.
                printf '%s' "${BACKUP_PASSWORD}" | run tee "${BACKUP_KEY_FILE}" > /dev/null && \
                run chmod 0600 "${BACKUP_KEY_FILE}"
            else
                info "Backup key ${BACKUP_KEY_FILE} already exists, keeping it."
            fi

            # Initialize the repository now so the first cron run never fails.
            if ! RESTIC_PASSWORD_FILE="${BACKUP_KEY_FILE}" \
                RESTIC_REPOSITORY="${BACKUP_REPO}" restic cat config >/dev/null 2>&1; then
                echo "Initializing Restic repository at ${BACKUP_REPO}..."
                run env RESTIC_PASSWORD_FILE="${BACKUP_KEY_FILE}" \
                    RESTIC_REPOSITORY="${BACKUP_REPO}" restic init
            else
                info "Restic repository already initialized."
            fi
        fi

        # Web roots live under /home/<user>/webapps per lib/lemper-create.sh,
        # so /home covers them; the account webapps dir is listed explicitly too.
        local LEMPER_ACCOUNT=${LEMPER_USERNAME:-"lemper"}
        local BACKUP_PATHS_RAW="/home /home/${LEMPER_ACCOUNT}/webapps /etc/lemper /etc/nginx"

        # Write the scheduled backup runner script.
        write_backup_script "${BACKUP_REPO}" "${BACKUP_PATHS_RAW}" || return 1

        # Register the cron job.
        register_backup_cron

        success "Automated backup (Restic) installed successfully."
        info "Repository: ${BACKUP_REPO} | Schedule: ${BACKUP_SCHEDULE:-daily} | Runner: ${BACKUP_SCRIPT}"
    else
        info "Automated backup installation skipped."
    fi
}

echo "[Backup (Restic) Installation]"

# Start running things from a call at the end so if this script is executed
# after a partial download it doesn't do anything.
init_backup_install "$@"
